#logging config

logging:
 level:
   org.yw: DEBUG
 file: ./springbootcamelesb.log
 root: WARN

#activemq setting
spring:
  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin
 
# expose actuator endpoint via HTTP
management:
  #info,health,camelroutes
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always
  server.port: 8080

info.app.name: SpringBoot ElasticSearch Demo
info.app.author: Yan Wang
info.app.encoding: UTF-8

soap.port: 9009
 
enable:
    eventnotifier: true