#logging config

logging:
 level:
   org.yw: DEBUG
 file: ./springbootcamelesb.log
 root: WARN
 
# expose actuator endpoint via HTTP
management:
 endpoints.web.exposure.include: info,health,camelroutes
 
enable:
    eventnotifier: true