#logging config

logging:
 level:
   org.yw: DEBUG
 file: /opt/springbootcamelesb/springbootcamelesb.log
 root: WARN
 
# expose actuator endpoint via HTTP
management:
 endpoints.web.exposure.include: info,health,camelroutes
 server.port: 8080

soap.port: 9009
 
enable:
    eventnotifier: true