#logging config

logging:
 level:
   org.yw: DEBUG
 file: ./springbootcamelesb.log
 root: WARN

#activemq setting
spring:
  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin
 
# expose actuator endpoint via HTTP
management:
 endpoints.web.exposure.include: info,health,camelroutes
 server.port: 8080

soap.port: 9009
 
enable:
    eventnotifier: true